using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

namespace com.dxz.config
{
	#pragma warning disable 414

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public partial class BGE_PlayerTemplate : BGEntity
	{

		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		public class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta)
			{
				return new BGE_PlayerTemplate(meta);
			}
			public BGEntity NewEntity(BGMetaEntity meta, BGId id)
			{
				return new BGE_PlayerTemplate(meta, id);
			}
		}
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
		{
			get
			{
				if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4804072661402498299,9070039680110677382));
				return _metaDefault;
			}
		}
		public static BansheeGz.BGDatabase.BGRepoEvents Events
		{
			get
			{
				return BGRepo.I.Events;
			}
		}
		private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
		public static int CountEntities
		{
			get
			{
				return MetaDefault.CountEntities;
			}
		}
		public System.String f_name
		{
			get
			{
				return _f_name[Index];
			}
			set
			{
				_f_name[Index] = value;
			}
		}
		public System.String f_ModelPath
		{
			get
			{
				return _f_ModelPath[Index];
			}
			set
			{
				_f_ModelPath[Index] = value;
			}
		}
		public System.Int32 f_TypeID
		{
			get
			{
				return _f_TypeID[Index];
			}
			set
			{
				_f_TypeID[Index] = value;
			}
		}
		public System.Int32 f_PlayerSide
		{
			get
			{
				return _f_PlayerSide[Index];
			}
			set
			{
				_f_PlayerSide[Index] = value;
			}
		}
		public System.String f_AnimCtrlPath
		{
			get
			{
				return _f_AnimCtrlPath[Index];
			}
			set
			{
				_f_AnimCtrlPath[Index] = value;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
		{
			get
			{
				if(_ufle12jhs77_f_name==null || _ufle12jhs77_f_name.IsDeleted) _ufle12jhs77_f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4908071365945281149,16999867891563802294));
				return _ufle12jhs77_f_name;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_ModelPath;
		public static BansheeGz.BGDatabase.BGFieldString _f_ModelPath
		{
			get
			{
				if(_ufle12jhs77_f_ModelPath==null || _ufle12jhs77_f_ModelPath.IsDeleted) _ufle12jhs77_f_ModelPath=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(4679753256403019760,4456270821865003957));
				return _ufle12jhs77_f_ModelPath;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_TypeID;
		public static BansheeGz.BGDatabase.BGFieldInt _f_TypeID
		{
			get
			{
				if(_ufle12jhs77_f_TypeID==null || _ufle12jhs77_f_TypeID.IsDeleted) _ufle12jhs77_f_TypeID=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4801261983998461549,10373708069641358526));
				return _ufle12jhs77_f_TypeID;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_PlayerSide;
		public static BansheeGz.BGDatabase.BGFieldInt _f_PlayerSide
		{
			get
			{
				if(_ufle12jhs77_f_PlayerSide==null || _ufle12jhs77_f_PlayerSide.IsDeleted) _ufle12jhs77_f_PlayerSide=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4802895137100867088,8160206131508906380));
				return _ufle12jhs77_f_PlayerSide;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_AnimCtrlPath;
		public static BansheeGz.BGDatabase.BGFieldString _f_AnimCtrlPath
		{
			get
			{
				if(_ufle12jhs77_f_AnimCtrlPath==null || _ufle12jhs77_f_AnimCtrlPath.IsDeleted) _ufle12jhs77_f_AnimCtrlPath=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5565137557193801781,16964449636374138802));
				return _ufle12jhs77_f_AnimCtrlPath;
			}
		}
		private static readonly BGE_PlayerTemplate.Factory _factory0_PFS = new BGE_PlayerTemplate.Factory();
		private static readonly BGE_PlayerAttTemplate.Factory _factory1_PFS = new BGE_PlayerAttTemplate.Factory();
		private BGE_PlayerTemplate() : base(MetaDefault)
		{
		}
		private BGE_PlayerTemplate(BGId id) : base(MetaDefault, id)
		{
		}
		private BGE_PlayerTemplate(BGMetaEntity meta) : base(meta)
		{
		}
		private BGE_PlayerTemplate(BGMetaEntity meta, BGId id) : base(meta, id)
		{
		}
		public static BGE_PlayerTemplate FindEntity(Predicate<BGE_PlayerTemplate> filter)
		{
			return MetaDefault.FindEntity(entity => filter==null || filter((BGE_PlayerTemplate) entity)) as BGE_PlayerTemplate;
		}
		public static List<BGE_PlayerTemplate> FindEntities(Predicate<BGE_PlayerTemplate> filter, List<BGE_PlayerTemplate> result=null, Comparison<BGE_PlayerTemplate> sort=null)
		{
			result = result ?? new List<BGE_PlayerTemplate>();
			_find_Entities_Result.Clear();
			MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BGE_PlayerTemplate) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BGE_PlayerTemplate) e1, (BGE_PlayerTemplate) e2));
			if (_find_Entities_Result.Count != 0)
			{
				for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BGE_PlayerTemplate) _find_Entities_Result[i]);
				_find_Entities_Result.Clear();
			}
			return result;
		}
		public static void ForEachEntity(Action<BGE_PlayerTemplate> action, Predicate<BGE_PlayerTemplate> filter=null, Comparison<BGE_PlayerTemplate> sort=null)
		{
			MetaDefault.ForEachEntity(entity => action((BGE_PlayerTemplate) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BGE_PlayerTemplate) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BGE_PlayerTemplate)e1,(BGE_PlayerTemplate)e2));
		}
		public static BGE_PlayerTemplate GetEntity(BGId entityId)
		{
			return (BGE_PlayerTemplate) MetaDefault.GetEntity(entityId);
		}
		public static BGE_PlayerTemplate GetEntity(int index)
		{
			return (BGE_PlayerTemplate) MetaDefault[index];
		}
		public static BGE_PlayerTemplate GetEntity(string entityName)
		{
			return (BGE_PlayerTemplate) MetaDefault.GetEntity(entityName);
		}
		public static BGE_PlayerTemplate NewEntity()
		{
			return (BGE_PlayerTemplate) MetaDefault.NewEntity();
		}
	}

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public partial class BGE_PlayerAttTemplate : BGEntity
	{

		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		public class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta)
			{
				return new BGE_PlayerAttTemplate(meta);
			}
			public BGEntity NewEntity(BGMetaEntity meta, BGId id)
			{
				return new BGE_PlayerAttTemplate(meta, id);
			}
		}
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
		{
			get
			{
				if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5659449348152244251,8647667149400694164));
				return _metaDefault;
			}
		}
		public static BansheeGz.BGDatabase.BGRepoEvents Events
		{
			get
			{
				return BGRepo.I.Events;
			}
		}
		private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
		public static int CountEntities
		{
			get
			{
				return MetaDefault.CountEntities;
			}
		}
		public System.String f_name
		{
			get
			{
				return _f_name[Index];
			}
			set
			{
				_f_name[Index] = value;
			}
		}
		public System.Int32 f_Attack
		{
			get
			{
				return _f_Attack[Index];
			}
			set
			{
				_f_Attack[Index] = value;
			}
		}
		public System.Int32 f_HP
		{
			get
			{
				return _f_HP[Index];
			}
			set
			{
				_f_HP[Index] = value;
			}
		}
		public System.Int32 f_MAXHP
		{
			get
			{
				return _f_MAXHP[Index];
			}
			set
			{
				_f_MAXHP[Index] = value;
			}
		}
		public System.Single f_Speed
		{
			get
			{
				return _f_Speed[Index];
			}
			set
			{
				_f_Speed[Index] = value;
			}
		}
		public System.Single f_AttackDis
		{
			get
			{
				return _f_AttackDis[Index];
			}
			set
			{
				_f_AttackDis[Index] = value;
			}
		}
		public System.Single f_FinalSkillDis
		{
			get
			{
				return _f_FinalSkillDis[Index];
			}
			set
			{
				_f_FinalSkillDis[Index] = value;
			}
		}
		public System.Collections.Generic.List<UnityEngine.Vector2> f_AnimPerArray
		{
			get
			{
				return _f_AnimPerArray[Index];
			}
			set
			{
				_f_AnimPerArray[Index] = value;
			}
		}
		public System.Collections.Generic.List<UnityEngine.Vector2> f_AnimPerSkillArray
		{
			get
			{
				return _f_AnimPerSkillArray[Index];
			}
			set
			{
				_f_AnimPerSkillArray[Index] = value;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
		{
			get
			{
				if(_ufle12jhs77_f_name==null || _ufle12jhs77_f_name.IsDeleted) _ufle12jhs77_f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4902157435381073776,16892590568760668305));
				return _ufle12jhs77_f_name;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Attack;
		public static BansheeGz.BGDatabase.BGFieldInt _f_Attack
		{
			get
			{
				if(_ufle12jhs77_f_Attack==null || _ufle12jhs77_f_Attack.IsDeleted) _ufle12jhs77_f_Attack=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5452420793651247992,11838837463659377809));
				return _ufle12jhs77_f_Attack;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_HP;
		public static BansheeGz.BGDatabase.BGFieldInt _f_HP
		{
			get
			{
				if(_ufle12jhs77_f_HP==null || _ufle12jhs77_f_HP.IsDeleted) _ufle12jhs77_f_HP=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5321008938629520910,4186046613848773530));
				return _ufle12jhs77_f_HP;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_MAXHP;
		public static BansheeGz.BGDatabase.BGFieldInt _f_MAXHP
		{
			get
			{
				if(_ufle12jhs77_f_MAXHP==null || _ufle12jhs77_f_MAXHP.IsDeleted) _ufle12jhs77_f_MAXHP=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5232586627472829592,7700795507944059061));
				return _ufle12jhs77_f_MAXHP;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Speed;
		public static BansheeGz.BGDatabase.BGFieldFloat _f_Speed
		{
			get
			{
				if(_ufle12jhs77_f_Speed==null || _ufle12jhs77_f_Speed.IsDeleted) _ufle12jhs77_f_Speed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5014726987416906021,736290781849097890));
				return _ufle12jhs77_f_Speed;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_AttackDis;
		public static BansheeGz.BGDatabase.BGFieldFloat _f_AttackDis
		{
			get
			{
				if(_ufle12jhs77_f_AttackDis==null || _ufle12jhs77_f_AttackDis.IsDeleted) _ufle12jhs77_f_AttackDis=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4721309408254525353,13514107901130360195));
				return _ufle12jhs77_f_AttackDis;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_FinalSkillDis;
		public static BansheeGz.BGDatabase.BGFieldFloat _f_FinalSkillDis
		{
			get
			{
				if(_ufle12jhs77_f_FinalSkillDis==null || _ufle12jhs77_f_FinalSkillDis.IsDeleted) _ufle12jhs77_f_FinalSkillDis=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4894226379896245465,6604659315393699507));
				return _ufle12jhs77_f_FinalSkillDis;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldListVector2 _ufle12jhs77_f_AnimPerArray;
		public static BansheeGz.BGDatabase.BGFieldListVector2 _f_AnimPerArray
		{
			get
			{
				if(_ufle12jhs77_f_AnimPerArray==null || _ufle12jhs77_f_AnimPerArray.IsDeleted) _ufle12jhs77_f_AnimPerArray=(BansheeGz.BGDatabase.BGFieldListVector2) MetaDefault.GetField(new BGId(5088260322191444203,5128140554332748719));
				return _ufle12jhs77_f_AnimPerArray;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldListVector2 _ufle12jhs77_f_AnimPerSkillArray;
		public static BansheeGz.BGDatabase.BGFieldListVector2 _f_AnimPerSkillArray
		{
			get
			{
				if(_ufle12jhs77_f_AnimPerSkillArray==null || _ufle12jhs77_f_AnimPerSkillArray.IsDeleted) _ufle12jhs77_f_AnimPerSkillArray=(BansheeGz.BGDatabase.BGFieldListVector2) MetaDefault.GetField(new BGId(5165617054098012439,6043281319077210302));
				return _ufle12jhs77_f_AnimPerSkillArray;
			}
		}
		private static readonly BGE_PlayerTemplate.Factory _factory0_PFS = new BGE_PlayerTemplate.Factory();
		private static readonly BGE_PlayerAttTemplate.Factory _factory1_PFS = new BGE_PlayerAttTemplate.Factory();
		private BGE_PlayerAttTemplate() : base(MetaDefault)
		{
		}
		private BGE_PlayerAttTemplate(BGId id) : base(MetaDefault, id)
		{
		}
		private BGE_PlayerAttTemplate(BGMetaEntity meta) : base(meta)
		{
		}
		private BGE_PlayerAttTemplate(BGMetaEntity meta, BGId id) : base(meta, id)
		{
		}
		public static BGE_PlayerAttTemplate FindEntity(Predicate<BGE_PlayerAttTemplate> filter)
		{
			return MetaDefault.FindEntity(entity => filter==null || filter((BGE_PlayerAttTemplate) entity)) as BGE_PlayerAttTemplate;
		}
		public static List<BGE_PlayerAttTemplate> FindEntities(Predicate<BGE_PlayerAttTemplate> filter, List<BGE_PlayerAttTemplate> result=null, Comparison<BGE_PlayerAttTemplate> sort=null)
		{
			result = result ?? new List<BGE_PlayerAttTemplate>();
			_find_Entities_Result.Clear();
			MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((BGE_PlayerAttTemplate) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((BGE_PlayerAttTemplate) e1, (BGE_PlayerAttTemplate) e2));
			if (_find_Entities_Result.Count != 0)
			{
				for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((BGE_PlayerAttTemplate) _find_Entities_Result[i]);
				_find_Entities_Result.Clear();
			}
			return result;
		}
		public static void ForEachEntity(Action<BGE_PlayerAttTemplate> action, Predicate<BGE_PlayerAttTemplate> filter=null, Comparison<BGE_PlayerAttTemplate> sort=null)
		{
			MetaDefault.ForEachEntity(entity => action((BGE_PlayerAttTemplate) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BGE_PlayerAttTemplate) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BGE_PlayerAttTemplate)e1,(BGE_PlayerAttTemplate)e2));
		}
		public static BGE_PlayerAttTemplate GetEntity(BGId entityId)
		{
			return (BGE_PlayerAttTemplate) MetaDefault.GetEntity(entityId);
		}
		public static BGE_PlayerAttTemplate GetEntity(int index)
		{
			return (BGE_PlayerAttTemplate) MetaDefault[index];
		}
		public static BGE_PlayerAttTemplate GetEntity(string entityName)
		{
			return (BGE_PlayerAttTemplate) MetaDefault.GetEntity(entityName);
		}
		public static BGE_PlayerAttTemplate NewEntity()
		{
			return (BGE_PlayerAttTemplate) MetaDefault.NewEntity();
		}
	}
	#pragma warning restore 414
}
